### ISSUE TITLE
Gọi là Issue mà chẳng có Issue :v 

### ISSUE THREAD

**Issue by MinhPT-99** [tattrung15/tattrung15.github.io#2]
10 điểm e ơi, bài làm tốt lắm, ko sai lỗi nào, ko chê vào đâu được. Vận dụng tốt CSS. Tuyệt vời e ạ.

**Comment by tattrung15** [comment]
Vâng a ơi 😊😊

Vào 7:54 CH Th 2, 14 thg 10 2019 Phan Tuấn Minh <notifications@github.com>
đã viết:
